### ISSUE TITLE
When using 8bit for loading, an error is reported

### ISSUE THREAD

**Issue by lcqlalala** [bfshi/TOAST#2]
training_args.model == 'llama-topdown-lora':
        model = LlamaTopDownLoRAForCausalLM.from_pretrained(
            model_args.model_name_or_path,
            cache_dir=training_args.cache_dir,
            _**load_in_8bit=True,
            torch_dtype=torch.float16,
            device_map=device_map,**_
        )
When using 8bit for loading (shown in bold), an error is reported：

Traceback (most recent call last):
  File "/mnt/ssd/lcq/TOAST-main/language_generation/train.py", line 307, in <module>
    train()
  File "/mnt/ssd/lcq/TOAST-main/language_generation/train.py", line 245, in train
    model = LlamaTopDownLoRAForCausalLM.from_pretrained(
  File "/home/ubuntu/anaconda3/envs/alpaca/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2760, in from_pretrained
    dispatch_model(model, device_map=device_map, offload_dir=offload_folder, offload_index=offload_index)
  File "/home/ubuntu/anaconda3/envs/alpaca/lib/python3.9/site-packages/accelerate/big_modeling.py", line 370, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/ubuntu/anaconda3/envs/alpaca/lib/python3.9/site-packages/accelerate/hooks.py", line 471, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/ubuntu/anaconda3/envs/alpaca/lib/python3.9/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/ubuntu/anaconda3/envs/alpaca/lib/python3.9/site-packages/accelerate/hooks.py", line 244, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/ubuntu/anaconda3/envs/alpaca/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 136, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
_**ValueError: prompt is on the meta device, we need a `value` to put in on 0.**_

**Comment by bfshi** [comment]
Hi, could you share the bash script you are using?

**Comment by lcqlalala** [comment]
torchrun --nproc_per_node=2 --master_port=2203 train.py \
    --model_name_or_path /mnt/ssd/lcq/alpaca-lora-main/model/models--decapoda-research--llama-7b-hf \
    --data_path ./alpaca_data.json \
    --bf16 True \
    --output_dir ./output \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 12 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --report_to "none" \
    --model "llama-topdown-lora" \
    --deepspeed "./configs/default_offload_opt_param.json"

**Comment by lcqlalala** [comment]
model = LlamaTopDownLoRAForCausalLM.from_pretrained(
model_args.model_name_or_path,
cache_dir=training_args.cache_dir,
_**load_in_8bit=True,
torch_dtype=torch.float16,
device_map=device_map,**_
)
I will comment out the bold code, no error, just OOM
